Algoritmo "EXERC4_1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ana Cristina
// Autor(a)    : Gabriel de Lima Nascimento
// Data atual  : 31/03/2020
Var
 numero1,numero2: inteiro
 resultado:real


Inicio

Escreva("Digite um número: ")
 Leia(numero1)

Escreva("Digite outro número: ")
 Leia(numero2)
 
 resultado <- numero1 * 2 * (numero2 / 2)
 
escreval("O resultado é: ", resultado)

Fimalgoritmo