Algoritmo "EXERC8_1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ana Cristina
// Autor(a)    : Gabriel de Lima Nascimento
// Data atual  : 31/03/2020
Var

metros_quadrados, galoes, valor:real

Inicio

escreval ("Quantos metros quadrados deseja simular:")
leia (metros_quadrados)

galoes:= metros_quadrados/18/6

escreval ("Quantidade de galões necessários:",galoes)
valor:=galoes*92

escreval ("Custo total:", valor)

Fimalgoritmo