algoritmo "EXERC1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ana Cristina
// Autor(a)    : Gabriel de Lima Nascimento
// Data atual  : 31/03/2020
var
a, c, d, r:inteiro
b:real

inicio

Escreval ("Digite a: ")
Leia(a)
a <- (a + 3)

  Escreval ("Digite b: ")
  Leia(b)
b <- (b ^ 2)

  Escreval ("Digite c: ")
  Leia(c)
c <- (c * 4) -2

  Escreval ("Digite d: ")
  Leia(d)
d <- (d * 2)

Escreval ("Sua senha é:" , a, b, c, d)

fimalgoritmo