Algoritmo "EXERC6"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ana Cristina
// Autor(a)    : Gabriel de Lima Nascimento
// Data atual  : 31/03/2020
Var
 peso,multa: inteiro


Inicio

escreva ("Digite o peso: ")
 leia(peso)

se (peso> 50) entao
multa <- (peso - 50) * 4

escreva ("multa à pagar: ", multa)
 senao

escreval ("não exite multa à ser paga ")
 fimse


Fimalgoritmo